# Generated by Django 4.0.1 on 2022-03-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
