# Generated by Django 4.0.1 on 2022-03-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_new_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
