# Generated by Django 4.0.1 on 2022-03-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
