# Generated by Django 4.0.1 on 2022-04-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
