# Generated by Django 4.0.1 on 2022-04-25 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 17, 29, 30, 354471, tzinfo=utc)),
        ),
    ]
