# Generated by Django 4.0.1 on 2022-05-06 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_message_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MongoTest',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 16, 19, 38, 747332, tzinfo=utc)),
        ),
    ]
