# Generated by Django 4.0.1 on 2022-07-03 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pud_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 6, 27, 2, 927842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 6, 27, 2, 927842, tzinfo=utc)),
        ),
    ]
