# Generated by Django 4.0.1 on 2022-07-04 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_alter_article_pud_date_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pud_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 6, 49, 26, 720112, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 6, 49, 26, 720112, tzinfo=utc)),
        ),
    ]
