# Generated by Django 4.0.1 on 2022-07-05 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_alter_article_pud_date_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pud_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 8, 14, 58, 392711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 8, 14, 58, 392711, tzinfo=utc)),
        ),
    ]
