# Generated by Django 4.0.1 on 2022-07-13 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_alter_article_myfile_alter_article_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='myfile',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 10, 32, 39, 826467, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 10, 32, 39, 828469, tzinfo=utc)),
        ),
    ]
