# Generated by Django 4.0.1 on 2022-07-24 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_alter_article_pub_date_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='floatfield',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 15, 59, 31, 422995, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 15, 59, 31, 424993, tzinfo=utc)),
        ),
    ]
